[package]
name = "gii"
version = "0.0.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
colored = "2.1.0"
crossterm = "0.27.0"
